import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import { authMiddleware } from "../lib/auth";
import searchRouter from "./search";
import analyticsRouter from "./analytics";
import usersRouter from "./users";
import clientsRouter from "./clients";
import contactsRouter from "./contacts";
import clientActivitiesRouter from "./clientActivities";
import quotesRouter from "./quotes";
import serviceCatalogRouter from "./serviceCatalog";
import proposalsRouter from "./proposals";
import invoicesRouter from "./invoices";
import receiptsRouter from "./receipts";
import salesDocumentsRouter from "./salesDocuments";
import communicationsRouter from "./communications";
import syncCommsRouter from "./syncComms";
import employeesRouter from "./employees";
import candidatesRouter from "./candidates";
import payrollRouter from "./payroll";
import inventoryRouter from "./inventory";
import vaultRouter from "./vault";
import flexRouter from "./flex";
import purchaseOrdersRouter from "./purchaseOrders";
import forgeRouter from "./forge";
import productionOrdersRouter from "./productionOrders";
import shipmentsRouter from "./shipments";
import flowRouter from "./flow";
import sprintRouter from "./sprint";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import transactionsRouter from "./transactions";
import expensesRouter from "./expenses";
import contractsRouter from "./contracts";
import reportsRouter from "./reports";
import visitorsRouter from "./visitors";
import filesRouter from "./files";
import dashboardSummaryRouter from "./dashboardSummary";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);

router.use(authMiddleware);
router.use(searchRouter);
router.use(analyticsRouter);
router.use(usersRouter);
router.use(clientsRouter);
router.use(contactsRouter);
router.use(clientActivitiesRouter);
router.use(quotesRouter);
router.use(serviceCatalogRouter);
router.use(proposalsRouter);
router.use(invoicesRouter);
router.use(receiptsRouter);
router.use(salesDocumentsRouter);
router.use(communicationsRouter);
router.use(syncCommsRouter);
router.use(employeesRouter);
router.use(candidatesRouter);
router.use(payrollRouter);
router.use(inventoryRouter);
router.use(vaultRouter);
router.use(flexRouter);
router.use(purchaseOrdersRouter);
router.use(forgeRouter);
router.use(productionOrdersRouter);
router.use(shipmentsRouter);
router.use(flowRouter);
router.use(sprintRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(transactionsRouter);
router.use(expensesRouter);
router.use(contractsRouter);
router.use(reportsRouter);
router.use(visitorsRouter);
router.use(filesRouter);
router.use(dashboardSummaryRouter);

export default router;
