import mongoose from 'mongoose';

const DocumentSequenceSchema = new mongoose.Schema({
  documentType: { type: String, required: true, unique: true },
  prefix: { type: String, required: true },
  financialYear: { type: String, default: '2526' },
  lastNumber: { type: Number, default: 0 },
  formatPattern: { type: String, default: '{prefix}-{fy}-{number:04d}' },
});

const ClientAddressSchema = new mongoose.Schema({
  clientId: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: true },
  addressType: { type: String, enum: ['Billing', 'Shipping', 'Both'], default: 'Both' },
  label: String,
  addressLine1: { type: String, required: true },
  addressLine2: String,
  city: { type: String, required: true },
  state: { type: String, required: true },
  stateCode: { type: String, required: true },
  pincode: { type: String, required: true },
  country: { type: String, default: 'India' },
  gstin: String,
  isDefault: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

// Quotations Collection
const QuotationSchema = new mongoose.Schema({
  quotationNumber: { type: String, required: true, unique: true },
  revisionNumber: { type: Number, default: 0 },
  clientId: { type: mongoose.Schema.Types.ObjectId, ref: 'Client', required: true },
  clientName: { type: String, required: true },
  clientGstin: String,
  billingAddressId: { type: mongoose.Schema.Types.ObjectId, ref: 'ClientAddress' },
  shippingAddressId: { type: mongoose.Schema.Types.ObjectId, ref: 'ClientAddress' },
  reference: String,
  quotationDate: { type: Date, required: true },
  validUntil: { type: Date, required: true },
  currency: { type: String, default: 'INR' },
  exchangeRate: { type: Number, default: 1.0 },
  placeOfSupply: String,
  subtotal: { type: Number, default: 0 },
  discountType: { type: String, enum: ['Percentage', 'Amount', 'None'], default: 'None' },
  discountValue: { type: Number, default: 0 },
  discountAmount: { type: Number, default: 0 },
  taxableAmount: { type: Number, default: 0 },
  cgstTotal: { type: Number, default: 0 },
  sgstTotal: { type: Number, default: 0 },
  igstTotal: { type: Number, default: 0 },
  cessTotal: Number,
  roundOff: { type: Number, default: 0 },
  grandTotal: { type: Number, default: 0 },
  paymentTerms: String,
  deliveryTimeline: String,
  notes: String,
  termsAndConditions: String,
  status: { type: String, enum: ['Draft', 'Sent', 'Revised', 'Accepted', 'Rejected', 'Expired', 'Cancelled'], default: 'Draft' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  items: [{
    sortOrder: { type: Number, default: 0 },
    itemId: { type: mongoose.Schema.Types.ObjectId, ref: 'InventoryItem' },
    itemType: { type: String, enum: ['Product', 'Service'], default: 'Product' },
    itemCode: String,
    description: { type: String, required: true },
    hsnSac: { type: String, default: '' },
    quantity: { type: Number, default: 1 },
    uom: { type: String, default: 'Nos' },
    rate: { type: Number, default: 0 },
    discountPercent: { type: Number, default: 0 },
    discountAmount: { type: Number, default: 0 },
    taxableAmount: { type: Number, default: 0 },
    cgstPercent: { type: Number, default: 0 },
    cgstAmount: { type: Number, default: 0 },
    sgstPercent: { type: Number, default: 0 },
    sgstAmount: { type: Number, default: 0 },
    igstPercent: { type: Number, default: 0 },
    igstAmount: { type: Number, default: 0 },
    cessPercent: Number,
    cessAmount: Number,
    lineTotal: { type: Number, default: 0 },
  }],
});

const Quotation = mongoose.model('Quotation', QuotationSchema);

export { DocumentSequenceSchema, ClientAddressSchema, Quotation };